#ifndef _MQTT_CLIENT_ERR_CODE_H_
#define _MQTT_CLIENT_ERR_CODE_H_

#ifdef __cplusplus
extern "C" {
#endif


typedef enum err_code {
    ERROR_CERT_VERIFY_FAIL  = -26,
    MQTT_CONNECT_BLOCK = -25,
    MQTT_TOPIC_FORMAT_ERROR = -24,
    MQTT_CONNACK_UNKNOWN_ERROR = -23,
    MQTT_CONANCK_UNACCEPTABLE_PROTOCOL_VERSION_ERROR = -22,
    MQTT_CONNACK_IDENTIFIER_REJECTED_ERROR = -21,
    MQTT_CONNACK_SERVER_UNAVAILABLE_ERROR = -20,
    MQTT_CONNACK_BAD_USERDATA_ERROR = -19,
    MQTT_CONNACK_NOT_AUTHORIZED_ERROR = -18,
    MQTT_CONNECT_ERROR = -17,
    MQTT_PING_PACKET_ERROR = -16,
    MQTT_CONNECT_PACKET_ERROR = -15,
    MQTT_CONNECT_ACK_PACKET_ERROR = -14,
    MQTT_NETWORK_CONNECT_ERROR = -13,
    MQTT_STATE_ERROR = -12,
    MQTT_SUBSCRIBE_PACKET_ERROR = -11,
    MQTT_SUBSCRIBE_ACK_PACKET_ERROR = -10,
    MQTT_UNSUBSCRIBE_PACKET_ERROR = -9,
    MQTT_PUBLISH_PACKET_ERROR = -8,
    MQTT_PUBLISH_ACK_PACKET_ERROR = -7,
    MQTT_NETWORK_ERROR = -6,
    ERROR_NO_MEM = -5,
    ERROR_CERTIFICATE_EXPIRED = -4,
    ERROR_MALLOC = -3,
    NULL_VALUE_ERROR = -2,
    FAIL_RETURN = -1,                       
    SUCCESS_RETURN = 0,
} mqtt_client_err_code_t;




#ifdef __cplusplus
}
#endif
#endif

